# Disseque uma variável, exibindo diversas características da mesma.
a = input('Digite algo: ')
print(f'O tipo da variável é: {type(a)}')
print(f'Só tem espaços? {a.isspace()}')
print(f'É um número? {a.isnumeric()}')
print(f'É um alfabético? {a.isalpha()}')
print(f'É um alfanumérico? {a.isalnum()}')
print(f'Esta em maíusculo? {a.isupper()}')
print(f'Está em minúsculo? {a.islower()}')
print(f'Está em capitalizada? {a.istitle()}')
